- include_role:
    name: update_cache


- name: Install Flask
  yum:
    name:
      - python3-flask
    state: present
    when: ansible_distribution == "CentOs" or ansible_distribution == "Amazon"
