- include_role:
    name: update_cache


- name: Install Node
  yum:
    name:
      - nodejs
      - npm
    state: latest
  when: ansible_distribution == "CentOs" or ansible_distribution == "Amazon"
