- include_role:
    name: install_postgres

- name: Create db user
  community.postgresql.postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password}}"
  become: true
  become_user: postgres

- name: Grant user access to db
  community.postgresql.postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    privs: all
    grant_option: false
  become: true
  become_user: postgres