- include_role:
    name: install_postgres

- name: Create db user
  community.postgresql.postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password}}"
  become: true
  become_user: postgres

- name: Create db
  become_user: postgres
  shell: psql -f /opt/app/db/init.sql

- name: "Allow md5 connection for the db user"
  postgresql_pg_hba:
    dest: "~/data/pg_hba.conf"
    contype: host
    databases: all
    method: md5
    users: "{{ db_user }}"
    create: true
  become: true
  become_user: postgres

- name: "Restart postgres"
  service:
    name: postgresql
    state: restarted