- name: App Deployment
  hosts: centos amazon
  become: true
  become_method: sudo
  vars_files:
    - vars.yml
  roles:
    - install_flask
    - install_node
    - install_postgres
    # - start_flask_service
    # - start_node_service