- include_role:
    name: update_cache


- name: Install Postgres
  yum:
    name:
      - postgresql15
      - postgresql15-server
      - python3-psycopg2
    state: latest
  when: ansible_distribution == "CentOs" or ansible_distribution == "Amazon"

- name: Check if postgresql is initialized
  stat:
    path: /var/lib/pgsql/data/pg_hba.conf
  register: postgres_data

- name: Initialize PostgresSQL
  shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists


- name: "Start and enable postgresql"
  service:
    name: postgresql 
    state: started 
    enabled: true