- include_role:
    name: update_cache


- name: Install Postgres
  ansible.builtin.yum:
    name:
      - postgresql-server
      - postgresql
    state: present
  when: ansible_distribution == "CentOs" or ansible_distribution == "Amazon"
