- include_role:
    name: update_cache


- name: Install Postgres
  dnf:
    name:
      - postgresql-server
      - postgresql
    state: latest
  when: ansible_distribution == "CentOs" or ansible_distribution == "Amazon"
