- include_role:
    name: update_cache


- name: Install Postgres
  yum:
    name:
      - postgresql15
    state: latest
  when: ansible_distribution == "CentOs" or ansible_distribution == "Amazon"

- name: Create app database
  postgresql_db:
    state: present
    name: "{{ db_name }}"
  become: true
  become_user: postgres

- name: "Create db user"
  postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: true
  become_user: postgres

- name: "Grant db user access to app db"
  postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: no
    privs: all
  become: true
  become_user: postgres