- include_role:
    name: update_cache


- name: Install Postgres
  yum:
    name:
      - postgresql15
      - python3-psycopg2
    state: latest
  when: ansible_distribution == "CentOs" or ansible_distribution == "Amazon"
